import { IProperty } from "@/interfaces/IProperty";
import { BannerImage } from "./images.routes";

export const buyRentProperties: IProperty[] = [
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
];

export const featuredListing: IProperty[] = [
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
  {
    id: "a8dj2k9pq",
    description: "PKR 2.2 Crore",
    bedrooms: "2",
    bathrooms: "2",
    area: { totalArea: "240", type: " Sq.ft" },
    type: "House",
    location: "Karachi",
    city: "Karachi",
    classification: "Plot",
    duesCleared: "cleared",
    features: {
      basicFeatures: [],
      facilities: [],
      nearbyPlaces: [],
      secondaryFeatures: [],
    },
    images: [
      {
        public_id: "",
        url: BannerImage,
      },
    ],
    allotmentLetter: {
      public_id: "",
      url: "",
    },
    name: "",
    price: { askingPrice: "", currency: "PKR" },
    purpose: "rent",
    status: "completion",
  },
];
