import { IBuyRentProperty } from "@/interfaces/IBuyRent";

export const buyRentProperties: IBuyRentProperty[] = [
  {
    id: "a8dj2k9pq",
    title: "PKR 2.2 Crore",
    bedRooms: "2",
    bathRooms: "2",
    area: "240 Sq.ft",
    type: "House",
    location: "Karachi",
  },
  {
    id: "w4e8tnv5g",
    title: "PKR 1.2 Crore",
    bedRooms: "3",
    bathRooms: "2",
    area: "2 Marla",
    type: "House",
    location: "Islamabad",
  },
  {
    id: "c9rmx8b2l",
    title: "PKR 3.5 Crore",
    bedRooms: "4",
    bathRooms: "2",
    area: "1 Kanal",
    type: "House",
    location: "Rawalpindi",
  },
  {
    id: "u57sh3zqj",
    title: "PKR 52.2 Crore",
    bedRooms: "5",
    bathRooms: "4",
    area: "10 Marla",
    type: "House",
    location: "Faisalabad",
  },
  {
    id: "n3k7f1vrp",
    title: "PKR 6.2 Crore",
    bedRooms: "3",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Karachi",
  },
  {
    id: "xq84n6jtw",
    title: "PKR 1.2 Crore",
    bedRooms: "4",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Islamabad",
  },
  {
    id: "jz5l7vc9k",
    title: "PKR 3.6 Crore",
    bedRooms: "5",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Rawalpindi",
  },
  {
    id: "t6k8vr4qx",
    title: "PKR 5.7 Crore",
    bedRooms: "5",
    bathRooms: "3",
    area: "10 Marla",
    type: "House",
    location: "Faisalabad",
  },
  {
    id: "b2w7d5lzp",
    title: "PKR 4.9 Crore",
    bedRooms: "2",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Karachi",
  },
];

export const featuredListing: IBuyRentProperty[] = [
  {
    id: "n3k7f1vrp",
    title: "PKR 6.2 Crore",
    bedRooms: "3",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Karachi",
  },
  {
    id: "xq84n6jtw",
    title: "PKR 1.2 Crore",
    bedRooms: "4",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Islamabad",
  },
  {
    id: "jz5l7vc9k",
    title: "PKR 3.6 Crore",
    bedRooms: "5",
    bathRooms: "2",
    area: "10 Marla",
    type: "House",
    location: "Rawalpindi",
  },
  {
    id: "a8dj2k9pq",
    title: "PKR 2.2 Crore",
    bedRooms: "2",
    bathRooms: "2",
    area: "240 Sq.ft",
    type: "House",
    location: "Karachi",
  },
  {
    id: "w4e8tnv5g",
    title: "PKR 1.2 Crore",
    bedRooms: "3",
    bathRooms: "2",
    area: "2 Marla",
    type: "House",
    location: "Islamabad",
  },
];
